parameters:
  GroupsAdminsSuffixForEmails: ''
  default-sender-email: ''
  customsendmail_editable_config_params:
   - 'GroupsAdminsSuffixForEmails'
   - 'default-sender-email'
services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Customsendmail\Service\:
    resource: 'services/*'

  # Allows to use controllers as services
  YesWiki\Customsendmail\Controller\:
    resource: 'controllers/*'