parameters:
  GroupsAdminsSuffixForEmails: ''
  default-sender-email: ''
  AreaFieldName: ''
  customsendmail_editable_config_params:
   - 'GroupsAdminsSuffixForEmails'
   - 'default-sender-email'
   - 'AreaFieldName'
services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Customsendmail\Service\:
    resource: 'services/*'
    exclude:
     - 'GroupManagementServiceInterface.php'

  # Allows to use controllers as services
  YesWiki\Customsendmail\Controller\:
    resource: 'controllers/*'

  YesWiki\Customsendmail\Service\ActionsBuilderService:
    decorates: YesWiki\Aceditor\Service\ActionsBuilderService
    decoration_on_invalid: null
    arguments:
      $parentActionsBuilderService: '@.inner'
  
  YesWiki\Customsendmail\Service\GroupManagementService:
    decorates: YesWiki\Groupmanagement\Service\GroupManagementService
    decoration_on_invalid: null