services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Customsendmail\Service\:
    resource: 'services/*'

  # Allows to use controllers as services
  YesWiki\Customsendmail\Controller\:
    resource: 'controllers/*'